# Generated by Django 4.1.7 on 2023-03-21 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashRedirect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_internal', models.BooleanField(default=True)),
                ('is_one_time', models.BooleanField(default=False)),
                ('require_login', models.BooleanField(default=True)),
                ('url', models.TextField()),
                ('secret', models.CharField(db_index=True, editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_access_at', models.DateTimeField(editable=False, null=True)),
            ],
        ),
    ]
