# Generated by Django 4.1.7 on 2023-03-21 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hredirect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashredirect',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hashredirect',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
