# Generated by Django 4.1.7 on 2023-03-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hredirect', '0002_hashredirect_description_alter_hashredirect_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashredirect',
            name='internal_arguments',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
